# Generated by Django 3.2.4 on 2022-04-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('shares', models.IntegerField()),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('buy_date', models.DateField()),
                ('invested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('sell_date', models.DateField()),
            ],
        ),
    ]
